export default function Float() {
    return (<div id="wd-float-divs">
        <h2>Float</h2>
        <div>
            <img className="wd-float-right"
                src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate esse labore tempora facilis suscipit quis distinctio itaque asperiores molestiae, nostrum facere, at natus? Natus in quis rerum iusto velit, nesciunt debitis eveniet molestias quam consequatur explicabo exercitationem itaque, expedita optio earum voluptatum fugit inventore quidem, laborum totam! Esse pariatur cum tenetur incidunt minima voluptate, eum, tempora architecto aut quibusdam fuga non inventore velit recusandae? Itaque consectetur assumenda ab ipsum beatae sapiente expedita! Tempore, ad tenetur accusamus inventore provident, rerum debitis adipisci ullam at corporis culpa. Perferendis placeat tempore quasi pariatur eius, amet natus fugit voluptatibus, enim deleniti praesentium, dolore perspiciatis veritatis. Exercitationem dolorem, est dolore itaque sunt, tenetur neque laborum cumque eveniet pariatur incidunt inventore possimus consequatur repellat dolores quo laboriosam consequuntur nemo magnam rem. Nihil tenetur deleniti placeat, veritatis illum minima porro sunt commodi, saepe sed id expedita nostrum deserunt quidem dignissimos libero reiciendis. Ducimus hic expedita similique nobis aut deleniti odit nihil quas, sit reprehenderit iste voluptatem quia, ratione sapiente cumque repudiandae ipsam dolores libero neque mollitia aperiam soluta molestiae excepturi! Perferendis at minus est officia expedita. Recusandae, asperiores minus optio autem dolores nostrum architecto magni nesciunt expedita placeat sint sed voluptates provident voluptate.
            <img className="wd-float-left"
                src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis laudantium natus officiis dolorem similique numquam, fugit fuga nesciunt! Assumenda totam quasi ipsa placeat est autem voluptatem iure quia eveniet. Quasi itaque impedit corrupti expedita ipsa aliquam quia ullam fugiat dolores qui aut temporibus beatae dolorum, quos pariatur porro voluptatibus architecto vel est in. Distinctio nulla assumenda nihil veniam quia repellendus error voluptates recusandae deserunt? Perspiciatis animi error natus sint consequatur excepturi, amet autem rerum veniam dolor? Dolorum blanditiis voluptatem saepe assumenda sunt quam id expedita reiciendis culpa, maiores, alias molestias nemo ducimus, unde optio iure repellat. Veritatis assumenda rerum, voluptas totam numquam ducimus nobis hic voluptate eligendi soluta. Tenetur sunt quis laudantium saepe fugiat dolorem id mollitia distinctio exercitationem, similique velit, odit, ipsa voluptate fugit qui vitae tempore. Laborum temporibus a veritatis, consectetur, quidem assumenda sequi atque quibusdam enim, accusamus asperiores quam odio? Neque quod sed nobis dolores voluptatum numquam aspernatur accusamus tempore temporibus fugit animi aliquid perferendis dolorum, minus unde harum voluptatibus amet id laboriosam quis magni eaque cupiditate? Earum, ex? Fugit, rem nesciunt eveniet iste dolorem, nihil ratione quisquam libero a autem est at quod laudantium nemo exercitationem consequatur temporibus similique sapiente eum recusandae incidunt quos dolorum doloremque. Ipsam provident soluta maiores odio ducimus harum dignissimos eligendi quis velit deleniti!
            <img className="wd-float-right"
                src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laboriosam ab omnis quidem quibusdam voluptatum. Iste, praesentium. Numquam asperiores eum dolorem officia! Suscipit illo, esse repellendus reiciendis voluptas ea et culpa dignissimos earum ab, eaque odit sequi deleniti maiores eveniet molestiae? Eius non tempore possimus alias perferendis nihil laboriosam recusandae placeat. Cum, tempora ab totam error pariatur dolorum dicta. Vero velit architecto ratione quia atque ipsa porro magni, quas incidunt repudiandae voluptatum. Itaque exercitationem quas laudantium ullam, animi, numquam a iure incidunt modi culpa recusandae, id optio et architecto cum quidem quibusdam natus aliquam aliquid dignissimos ipsa obcaecati sunt! Soluta magnam ullam sed debitis blanditiis, placeat corporis aperiam iusto eligendi ea? Aliquid sequi dolorum minima similique magnam ducimus quae quisquam nesciunt autem fugiat? A recusandae cumque ea autem delectus adipisci alias consectetur repellat amet omnis, facere quia dicta sapiente nisi sint similique atque tempore neque itaque molestias magnam asperiores, aliquam voluptatibus. Quaerat, soluta ratione amet a doloribus deleniti praesentium nam, laborum modi ipsam inventore labore in quae exercitationem quam saepe tempora aspernatur totam debitis natus neque? Voluptatum, aliquam! Alias impedit omnis quasi et odit, sapiente illum laboriosam eaque natus quod molestiae voluptatem hic deserunt totam quas at voluptatibus. Corporis nesciunt eaque debitis quaerat cum eius fugit dolores doloremque asperiores, obcaecati quia voluptatibus molestiae, consequuntur possimus, aliquid iusto corrupti itaque. Quibusdam aliquid corporis ipsam voluptate tempore quis eum nemo necessitatibus inventore, officiis reiciendis ex quas impedit architecto quidem exercitationem, molestiae aspernatur repellat sit assumenda commodi amet.
            <img className="wd-float-left"
                src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem fugit sequi eligendi ea facilis, asperiores commodi cum maiores ipsam consequatur animi ex. Saepe harum obcaecati neque tempora nobis consequatur illum praesentium ipsa odit voluptas eligendi voluptate sapiente nostrum ex ullam facilis ut inventore rerum beatae, accusamus odio molestiae tempore provident! Quasi tempore dolorem expedita provident quisquam ipsa itaque, nihil rerum labore odit, voluptate ipsum vitae omnis ab perferendis rem! Rem debitis, sit ad nam culpa facere amet mollitia at, numquam reprehenderit voluptate aut incidunt, quo alias perferendis ut omnis. Provident doloribus consequuntur voluptatum vero quo quod alias aperiam ab, quisquam a facere consequatur repudiandae consectetur adipisci cum, in ut voluptatem quia nisi, voluptates at hic? Labore, voluptatem rerum? Itaque repudiandae accusamus, impedit debitis cupiditate iusto alias illo recusandae qui tenetur quaerat, quisquam fugit, assumenda aliquid quae modi voluptates exercitationem vel saepe soluta asperiores. Possimus fugit soluta nisi totam sint dolore. Neque repellendus maxime pariatur quo fugit enim quod explicabo temporibus quos, incidunt modi fuga aliquid ducimus reiciendis laborum, expedita, aperiam magni nesciunt a similique cumque asperiores facilis. Accusamus assumenda maiores necessitatibus placeat sint deleniti debitis officiis dolorem porro quo iusto iure laborum culpa blanditiis, delectus eius similique, architecto quidem qui repellendus iste accusantium nulla eveniet. Inventore nobis corporis autem! Quibusdam alias distinctio accusamus suscipit assumenda odio dolor accusantium, dolorum amet facere debitis vel blanditiis, velit itaque corrupti nostrum ipsum soluta beatae. Iusto, delectus dolore at, perferendis possimus optio assumenda tempora quidem deleniti provident laboriosam blanditiis sunt voluptatibus ipsa impedit voluptates unde corporis nostrum libero ex architecto corrupti! Unde, dolores expedita voluptate quaerat aperiam consectetur.
            <div className="wd-float-done"></div>
        </div>
        <div className="wd-float-left wd-dimension-portrait wd-bg-color-yellow">
            Yellow </div>
        <div className="wd-float-left wd-dimension-portrait wd-bg-color-blue wd-fg-color-white">
            Blue </div>
        <div className="wd-float-left wd-dimension-portrait wd-bg-color-red">
            Red </div>
        <img className="wd-float-right"
            src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
        <div className="wd-float-done"></div>

    </div>
    );
}